### ISSUE TITLE
Support for pydantic version 2

### ISSUE THREAD

**Issue by mfrancke** [h2020charisma/ramanchada2#103]
Hi,

I'm managing a python environment having multiple users and use-cases. One group of users request the ramanchada2 which we then make available.

It seems ramanchada2 requires pydantic v1. This causes issues for us, since we have other packages relying on pydantic v2.

Do you have plans for upgrading ramanchada2 to pydantic v2?

Best regards
Mathias

**Comment by vedina** [comment]
we need pydantic2 update ourselves, but are with limited resources at the moment,  good chance this will change next month

**Comment by mfrancke** [comment]
Good to hear! We will be looking forward to that

**Comment by kerberizer** [comment]
Resolved by #136
