### ISSUE TITLE
Replace `pyhht` with `emd`

### ISSUE THREAD

**Issue by kerberizer** [h2020charisma/ramanchada2#105]
We currently depend on https://github.com/jaidevd/pyhht, but it isn't actively maintained and there hasn't been a new PyPI release since 2017. As suggested by @georgievgeorgi, we could replace it with https://gitlab.com/emd-dev/emd

For further reference:

https://emd.readthedocs.io/en/stable/emd_tutorials/01_sifting/index.html

```py
imf = emd.sift.sift(xy, max_imfs=3)
```

**Comment by vedina** [comment]
@evg-mar please create a test for HHT, then we'll merge pull request
