### ISSUE TITLE
make sure emd module is in requirements

### ISSUE THREAD

**Issue by vedina** [h2020charisma/ramanchada2#135]
after a fresh conda install  from requirements.txt the statement in spectrum\__init__.py `import emd`  fails 

> No module named 'emd'

please check

**Comment by kerberizer** [comment]
> after a fresh conda install from requirements.txt the statement in spectrum__init__.py `import emd` fails
> 
> > No module named 'emd'
> 
> please check

Conda doesn't use the `requirements.txt` file. It uses `environment.yml` and this should work. In fact, it relies almost completely on `setup.py` itself—which does include emd (the tests would fail otherwise). We should probably get rid of these files -- requirements.txt and requirements-dev.txt -- unless @georgievgeorgi objects to it.

@vedina How can I reproduce the problem? `conda env create` (or `update`) does seem to work.

**Comment by vedina** [comment]
Well I did conda env create and it did not work

На ср, 31.07.2024 г., 12:34 ч. Luchesar ILIEV ***@***.***>
написа:

**Comment by kerberizer** [comment]
> Well I did conda env create and it did not work

Ok, trying to guess here, so here's what I did apart from the initial test on Linux (in plain terminal):

Tested on Windows too, in case some dependency isn't available as a pre-built wheel or cannot be built properly.
- installed Miniforge (should be the same with Miniconda, as only diff is default channels and environment.yml sets conda-forge as primary channel anyway)
- fetched the Zip archive of the main branch
- performed `conda env create`
- `conda activate ramanchada2`
- `python` -> `import emd`
This works.

Tested in Visual Studio Code (on Linux).
- opened repo directory
- used "Python: Create environment..." from command palette (F1 or Ctrl+Shift+P)
- Selected "Conda" from the drop-down (which would create a new env in `.conda` subdir)
- opened a **new** command prompt (VS Code warns that an extension wants the existing one to be restarted)
- `python` -> `import emd`
This also works.

At this point I have no other specific ideas to test. There are way too many possibilities. @vedina Could you possibly explain in more elaborate steps how the problem emerges for you?

**Comment by vedina** [comment]
- activated previously created ramanchada2 conda env
- run conda env update
- selected the env in jupyter notebook in vscode
- import ramanchada2 fails

На ср, 31.07.2024 г., 14:43 ч. Luchesar ILIEV ***@***.***>
написа:

**Comment by kerberizer** [comment]
> - activated previously created ramanchada2 conda env - run conda env update - selected the env in jupyter notebook in vscode - import ramanchada2 fails

@vedina that was very helpful, thanks! Here are a few questions/suggestions:

1) Have you tried removing the environment and then creating it anew?
2) Even easier, you can create a fresh environment with a different name, e.g. `conda env update -n rc2` (when creating new environment, `create` and `update` are mostly interchangeable).
3) Make sure that you select the same environment as the one that was created/updated. If no name is supplied with the `-n <name>` option, the default name from `environment.yml` file is `ramanchada2`.

In my tests -- with fresh environments -- running jupyter notebooks (in VScode) from the examples folder works fine.

**Comment by vedina** [comment]
- yes, fresh environment worked
- in the old environment, after conda update it was still failing, but after pip install emd it was working.  So my assumption was emd is missing in the configuration conda is using ( wrongly referring to requirements.txt though)
