### ISSUE TITLE
add support for File objects in spectrum.from_local_file  

### ISSUE THREAD

**Issue by vedina** [h2020charisma/ramanchada2#157]
add support for File objects in spectrum.from_local_file , in addition to current file names

useful when used in backend implementations

**Comment by georgievgeorgi** [comment]
If the filename is not known to the `from_local_file` function, the file type cannot be deduced by the filename, so the file object should always be given with the file type. Do you see any related issues?

**Comment by vedina** [comment]
currently I pass the file name as well (as below).  file extension only is an option as well 
one use case is sending a file through multipart web form,  we obtain file object and file names (without paths) 

files: list[UploadFile] = File(...),
FastAPI class is https://fastapi.tiangolo.com/reference/uploadfile/ , all frameworks always have File object and a name

```
def read_spectrum_native(file,f_name,prefix="rcapi_"):
    native_filename=None
    try:
        filename, file_extension = os.path.splitext(f_name)
        # because rc2works with file paths only, no url nor file objects
        with tempfile.NamedTemporaryFile(delete=False,prefix=prefix,suffix=file_extension) as tmp:
            shutil.copyfileobj(file,tmp)
            native_filename = tmp.name
        spe =  from_local_file(native_filename)
        return spe
    except Exception as err:
        raise err
    finally:
        if native_filename!=None:
            os.remove(native_filename)
```            

another case is obtaining the file as a stream , e.g. load directly from URL  without writing locally
