### ISSUE TITLE
FWHM calculation is not working well from the fit

### ISSUE THREAD

**Issue by nicocopez** [h2020charisma/ramanchada2#174]
Georgi and I could see that if we calculate the fwhm from the sigma, it gives the right values. However when getting the values from fitres, they are wrong. For example, when fitting neon, many of the peaks give the same fwhm.

**Comment by georgievgeorgi** [comment]
I created a test which shows that everything works as expected. Could it be something wrong on your side?

**Comment by georgievgeorgi** [comment]
seems not reproducible
