### ISSUE TITLE
old_spe is not used

### ISSUE THREAD

**Issue by vedina** [h2020charisma/ramanchada2#40]
https://github.com/h2020charisma/ramanchada2/blob/78db9c6107d3ceeb8bbebb2ac6a2a5dfd23cb3b9/src/ramanchada2/spectrum/filters/sharpen_lines.py#L59

**Comment by georgievgeorgi** [comment]
`new_spe` is a hard copy of `old_spe`, so results should be OK. Anyway `old_spe` is to be used, as you correctly suggest.
