### ISSUE TITLE
Does convolution to a single delta line works?

### ISSUE THREAD

**Issue by nicocopez** [h2020charisma/ramanchada2#64]
I have tried to reproduce the example for generating synthetic spectra starting with two delta lines. It works to me, the same as in the example. 

```
spe0 = rc2.spectrum.from_delta_lines(deltas={585:100, 700:150}, nbins=1000)
spe0.plot()
spe1 = spe0.convolve(lineshape='gaussian', sigma=2)
spe1.plot()
```

However, if I only want to have one peak, the plot only shows a line (and no horizontal line) for the delta line plot, but also for the convoluted function.

```
spe0 = rc2.spectrum.from_delta_lines(deltas={585:100}, nbins=1000)
spe0.plot()
spe1 = spe0.convolve(lineshape='gaussian', sigma=2)
spe1.plot()
```

Am I doing something wrong or it isn't supposed to work like this?

![imagen](https://user-images.githubusercontent.com/47475896/222199159-3a92c33c-7e90-4248-91ed-b1949e834cae.png)
![imagen](https://user-images.githubusercontent.com/47475896/222199297-eeb7063c-12cb-4406-bc60-40de87a61164.png)

**Comment by georgievgeorgi** [comment]
Fixed. An explanation is available in the commit message.
