### ISSUE TITLE
Detailed information about "polyharmonic spline"

### ISSUE THREAD

**Issue by georgievgeorgi** [h2020charisma/ramanchada2#93]
As polyharmonic spline is part of the x-axis calibration procedure, we need to have it implemented in ramanchada2. We know that polyharmonic spline by itself doesn't provide the needed results. Could you please provide the details needed to implement the entire x-axis calibration procedure?

**Comment by vedina** [comment]
I used https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RBFInterpolator.html with thin_plate_spline in https://h2020charisma.github.io/ramanchada2/ramanchada2/protocols/calibration.html#XCalibrationComponent
